// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportFavorites():Promise<string>;

export function GetFavorites():Promise<Array<string>>;

export function GetFonts():Promise<Array<main.FontInfo>>;

export function ImportFavorites():Promise<number>;

export function IsFavorite(arg1:string):Promise<boolean>;

export function ListFonts():Promise<Array<string>>;

export function ToggleFavorite(arg1:string):Promise<boolean>;
