// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFonts():Promise<Array<main.FontInfo>>;

export function ListFonts():Promise<Array<string>>;
