// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFavorites() {
  return window['go']['main']['App']['ExportFavorites']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFonts() {
  return window['go']['main']['App']['GetFonts']();
}

export function ImportFavorites() {
  return window['go']['main']['App']['ImportFavorites']();
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function ListFonts() {
  return window['go']['main']['App']['ListFonts']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
